site_name: IOWA documentation (Lite)
site_url: 'https://ioterop.github.io/IOWA/'
repo_url: 'https://github.com/IOTEROP/IOWA'
copyright: 'Copyright &copy; 2020 IoTerop'

theme:
  name: "material"
#  icon:
#    logo: assets
  palette:
    primary: "blue"
  language: 'en'

extra:
  social:
    - icon: fontawesome/solid/globe-americas
      link: https://ioterop.com/
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/IOTEROP
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ioteropcompany
      name: Twitter


markdown_extensions:
  # Code highlighting in ``` ``` blocks
  - codehilite:
      guess_lang: true
        # Table of Contents
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # block-styled side content
  ### - admonition
  # linkifies URL and email links without having to wrap them in Markdown syntax. Also, allows shortens repository issue, pull request, and commit links.
  ###- pymdownx.magiclink
  # Task lists (https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/)
  ###- pymdownx.tasklist:
  ###    custom_checkbox: true
  # Highlight words with ==mark me==
  ###- pymdownx.mark
  # Adds support for deletion ~~Delete me~~ and subscript text~a\ subscript~
  ###- pymdownx.tilde
  # This extension is a convenience extension which includes many pymdownx extensions
  # (https://facelessuser.github.io/pymdown-extensions/extensions/extra/)
  ###- pymdownx.extra
  # (https://facelessuser.github.io/pymdown-extensions/extensions/details/)
  ###- pymdownx.details
  # Adds syntax for defining footnotes in Markdown documents (https://python-markdown.github.io/extensions/footnotes/)
  - footnotes
  # Adds the ability to define abbreviations
  - abbr
  # Include files in other documents like {!some/dir/in/docs/filename.md!}
  ###- markdown_include.include:
  ###    base_path: docs
  # Metadata support in pages
  # (https://squidfunk.github.io/mkdocs-material/extensions/metadata/)
  ###- meta:



nav:
  - Home: index.md
  - License.md
  - Changelog.md
  - Overview: LwM2MOverview.md
  - Evaluation Kit: EvaluationKit.md
  - Abstraction Layer: AbstractionLayer.md
  - Common APIs: CommonAPI.md
  - Client APIs: ClientAPI.md
  - Server APIs: ServerAPI.md
  - Bootstrap Server APIs: BootstrapServerAPI.md
  - Utils APIs: UtilsAPI.md
  - Deprecated APIs: DeprecatedAPI.md
  - OpenSource Licenses: OpenSourceLicenses.md
