/**********************************************
*
*  _________ _________ ___________ _________
* |         |         |   |   |   |         |
* |_________|         |   |   |   |    _    |
* |         |    |    |   |   |   |         |
* |         |    |    |           |         |
* |         |    |    |           |    |    |
* |         |         |           |    |    |
* |_________|_________|___________|____|____|
*
* Copyright (c) 2020 IoTerop.
* All rights reserved.
*
* This program and the accompanying materials
* are made available under the terms of
* IoTerop’s IOWA License (LICENSE.TXT) which
* accompany this distribution.
*
**********************************************/

#ifndef _IOWA_PRV_CORE_BACKWARD_COMPATIBILITY_CONFIG_
#define _IOWA_PRV_CORE_BACKWARD_COMPATIBILITY_CONFIG_

/**********************************************
* Set IOWA objects configuration for backward compatibility.
* This will be deleted when the IOWA_xx_RSC_xx_REMOVE defines will be deleted.
**********************************************/

// Check that IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_APN
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_APN can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_AUTO_SELECT_APN_DEVICE
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_AUTO_SELECT_APN_DEVICE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_ENABLE_STATUS
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_ENABLE_STATUS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_USER_NAME
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_USER_NAME can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SECRET
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SECRET can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_RECONNECT_SCHEDULE
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_RECONNECT_SCHEDULE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_VALIDITY
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_VALIDITY can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_TIME
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_TIME can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_RESULT
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_RESULT can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_REJECT_CAUSE
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_REJECT_CAUSE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONNECTION_END_TIME
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONNECTION_END_TIME can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_BYTES_SENT
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_BYTES_SENT can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_BYTES_RECEIVED
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_BYTES_RECEIVED can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_IP_ADDRESS
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_IP_ADDRESS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PREFIX_LENGTH
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PREFIX_LENGTH can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SUBNET_MASK
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SUBNET_MASK can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_GATEWAY
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_GATEWAY can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PRIMARY_DNS_ADDRESS
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PRIMARY_DNS_ADDRESS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SECONDARY_DNS_ADDRESS
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SECONDARY_DNS_ADDRESS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_QCI
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_QCI can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_PACKETS_SENT
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_PACKETS_SENT can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PDN_TYPE
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PDN_TYPE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_APN_RATE_CONTROL
#error "IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_APN_RATE_CONTROL can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on APN Connection Profile Object.
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_APN_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_APN
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_AUTO_SELECT_APN_DEVICE_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_AUTO_SELECT_APN_DEVICE
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_ENABLE_STATUS_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_ENABLE_STATUS
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_USER_NAME_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_USER_NAME
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_SECRET_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SECRET
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_RECONNECT_SCHEDULE_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_RECONNECT_SCHEDULE
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_VALIDITY_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_VALIDITY
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_CONN_ESTABLISHMENT_TIME_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_TIME
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_CONN_ESTABLISHMENT_RESULT_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_RESULT
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_CONN_ESTABLISHMENT_REJECT_CAUSE_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONN_ESTABLISHMENT_REJECT_CAUSE
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_CONNECTION_END_TIME_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_CONNECTION_END_TIME
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_TOTAL_BYTES_SENT_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_BYTES_SENT
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_TOTAL_BYTES_RECEIVED_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_BYTES_RECEIVED
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_IP_ADDRESS_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_IP_ADDRESS
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_PREFIX_LENGTH_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PREFIX_LENGTH
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_SUBNET_MASK_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SUBNET_MASK
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_GATEWAY_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_GATEWAY
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_PRIMARY_DNS_ADDRESS_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PRIMARY_DNS_ADDRESS
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_SECONDARY_DNS_ADDRESS_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_SECONDARY_DNS_ADDRESS
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_QCI_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_QCI
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_TOTAL_PACKETS_SENT_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_TOTAL_PACKETS_SENT
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_PDN_TYPE_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_PDN_TYPE
#endif
#ifndef IOWA_APN_CONNECTION_PROFILE_RSC_APN_RATE_CONTROL_REMOVE
#define IOWA_APN_CONNECTION_PROFILE_SUPPORT_RSC_APN_RATE_CONTROL
#endif

// Check that IOWA_BEARER_SELECTION_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_PREFERRED_COMM_BEARER
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_PREFERRED_COMM_BEARER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSSI_GSM
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSSI_GSM can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSCP_UMTS
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSCP_UMTS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSRP_LTE
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSRP_LTE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSSI_EV_DO
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSSI_EV_DO can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_CELL_LOCK_LIST
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_CELL_LOCK_LIST can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_OPERATOR_LIST
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_OPERATOR_LIST can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_OPERATOR_LIST_MODE
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_OPERATOR_LIST_MODE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_AVAILABLE_PLMNS
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_AVAILABLE_PLMNS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSRP_NB_IOT
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSRP_NB_IOT can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_PLMN_SEARCH_TIMER
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_PLMN_SEARCH_TIMER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_BEARER_SELECTION_SUPPORT_RSC_ATTACH_WO_PDN_CONNECTION
#error "IOWA_BEARER_SELECTION_SUPPORT_RSC_ATTACH_WO_PDN_CONNECTION can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on Bearer Selection Object.
#define IOWA_SUPPORT_BEARER_SELECTION_OBJECT
#ifndef IOWA_BEARER_SELECTION_RSC_PREFERRED_COMM_BEARER_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_PREFERRED_COMM_BEARER
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_ACCEPTABLE_RSSI_GSM_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSSI_GSM
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_ACCEPTABLE_RSCP_UMTS_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSCP_UMTS
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_ACCEPTABLE_RSRP_LTE_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSRP_LTE
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_ACCEPTABLE_RSSI_EV_DO_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSSI_EV_DO
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_CELL_LOCK_LIST_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_CELL_LOCK_LIST
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_OPERATOR_LIST_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_OPERATOR_LIST
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_OPERATOR_LIST_MODE_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_OPERATOR_LIST_MODE
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_AVAILABLE_PLMNS_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_AVAILABLE_PLMNS
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_ACCEPTABLE_RSRP_NB_IOT_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_ACCEPTABLE_RSRP_NB_IOT
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_PLMN_SEARCH_TIMER_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_PLMN_SEARCH_TIMER
#endif
#ifndef IOWA_BEARER_SELECTION_RSC_ATTACH_WO_PDN_CONNECTION_REMOVE
#define IOWA_BEARER_SELECTION_SUPPORT_RSC_ATTACH_WO_PDN_CONNECTION
#endif

// Check that IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_SMSC_ADDRESS
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_SMSC_ADDRESS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_DISABLE_RADIO_PERIOD
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_DISABLE_RADIO_PERIOD can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_MODULE_ACTIVATION_CODE
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_MODULE_ACTIVATION_CODE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_PSM_TIMER
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_PSM_TIMER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_ACTIVE_TIMER
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_ACTIVE_TIMER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_PLMN_RATE_CONTROL
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_PLMN_RATE_CONTROL can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_IU_MODE
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_IU_MODE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_WB_S1_MODE
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_WB_S1_MODE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_NB_S1_MODE
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_NB_S1_MODE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_A_GB_MODE
#error "IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_A_GB_MODE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on Cellular Connectivity Object.
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_SMSC_ADDRESS_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_SMSC_ADDRESS
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_DISABLE_RADIO_PERIOD_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_DISABLE_RADIO_PERIOD
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_MODULE_ACTIVATION_CODE_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_MODULE_ACTIVATION_CODE
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_PSM_TIMER_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_PSM_TIMER
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_ACTIVE_TIMER_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_ACTIVE_TIMER
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_PLMN_RATE_CONTROL_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_PLMN_RATE_CONTROL
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_EDRX_PARAM_IU_MODE_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_IU_MODE
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_EDRX_PARAM_WB_S1_MODE_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_WB_S1_MODE
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_EDRX_PARAM_NB_S1_MODE_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_NB_S1_MODE
#endif
#ifndef IOWA_CELLULAR_CONNECTIVITY_RSC_EDRX_PARAM_A_GB_MODE_REMOVE
#define IOWA_CELLULAR_CONNECTIVITY_SUPPORT_RSC_EDRX_PARAM_A_GB_MODE
#endif

// Check that IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_LINK_QUALITY
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_LINK_QUALITY can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_ROUTER_IP_ADDR
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_ROUTER_IP_ADDR can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_LINK_USAGE
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_LINK_USAGE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_APN
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_APN can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_CELL_ID
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_CELL_ID can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_SMNC
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_SMNC can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_SMCC
#error "IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_SMCC can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on Connectivity Monitoring Object.
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_LINK_QUALITY_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_LINK_QUALITY
#endif
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_ROUTER_IP_ADDR_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_ROUTER_IP_ADDR
#endif
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_LINK_USAGE_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_LINK_USAGE
#endif
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_APN_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_APN
#endif
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_CELL_ID_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_CELL_ID
#endif
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_SMNC_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_SMNC
#endif
#ifndef IOWA_CONNECTIVITY_MONITORING_RSC_SMCC_REMOVE
#define IOWA_CONNECTIVITY_MONITORING_SUPPORT_RSC_SMCC
#endif

// Check that IOWA_DEVICE_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_DEVICE_SUPPORT_RSC_MANUFACTURER
#error "IOWA_DEVICE_SUPPORT_RSC_MANUFACTURER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_MODEL_NUMBER
#error "IOWA_DEVICE_SUPPORT_RSC_MODEL_NUMBER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_SERIAL_NUMBER
#error "IOWA_DEVICE_SUPPORT_RSC_SERIAL_NUMBER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_FIRMWARE_VERSION
#error "IOWA_DEVICE_SUPPORT_RSC_FIRMWARE_VERSION can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_FACTORY_RESET
#error "IOWA_DEVICE_SUPPORT_RSC_FACTORY_RESET can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_POWER_SOURCE
#error "IOWA_DEVICE_SUPPORT_RSC_POWER_SOURCE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_BATTERY
#error "IOWA_DEVICE_SUPPORT_RSC_BATTERY can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_RESET_ERROR
#error "IOWA_DEVICE_SUPPORT_RSC_RESET_ERROR can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_CURRENT_TIME
#error "IOWA_DEVICE_SUPPORT_RSC_CURRENT_TIME can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_UTC_OFFSET
#error "IOWA_DEVICE_SUPPORT_RSC_UTC_OFFSET can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_TIMEZONE
#error "IOWA_DEVICE_SUPPORT_RSC_TIMEZONE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_DEVICE_TYPE
#error "IOWA_DEVICE_SUPPORT_RSC_DEVICE_TYPE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_HARDWARE_VERSION
#error "IOWA_DEVICE_SUPPORT_RSC_HARDWARE_VERSION can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_SOFTWARE_VERSION
#error "IOWA_DEVICE_SUPPORT_RSC_SOFTWARE_VERSION can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_MEMORY_TOTAL
#error "IOWA_DEVICE_SUPPORT_RSC_MEMORY_TOTAL can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_MEMORY_FREE
#error "IOWA_DEVICE_SUPPORT_RSC_MEMORY_FREE can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_DEVICE_SUPPORT_RSC_EXTERNAL_INFO
#error "IOWA_DEVICE_SUPPORT_RSC_EXTERNAL_INFO can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on Device Object.
#ifndef IOWA_DEVICE_RSC_MANUFACTURER_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_MANUFACTURER
#endif
#ifndef IOWA_DEVICE_RSC_MODEL_NUMBER_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_MODEL_NUMBER
#endif
#ifndef IOWA_DEVICE_RSC_SERIAL_NUMBER_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_SERIAL_NUMBER
#endif
#ifndef IOWA_DEVICE_RSC_FIRMWARE_VERSION_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_FIRMWARE_VERSION
#endif
#ifndef IOWA_DEVICE_RSC_FACTORY_RESET_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_FACTORY_RESET
#endif
#ifndef IOWA_DEVICE_RSC_POWER_SOURCE_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_POWER_SOURCE
#endif
#ifndef IOWA_DEVICE_RSC_BATTERY_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_BATTERY
#endif
#ifndef IOWA_DEVICE_RSC_RESET_ERROR_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_RESET_ERROR
#endif
#ifndef IOWA_DEVICE_RSC_CURRENT_TIME_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_CURRENT_TIME
#endif
#ifndef IOWA_DEVICE_RSC_UTC_OFFSET_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_UTC_OFFSET
#endif
#ifndef IOWA_DEVICE_RSC_TIMEZONE_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_TIMEZONE
#endif
#ifndef IOWA_DEVICE_RSC_DEVICE_TYPE_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_DEVICE_TYPE
#endif
#ifndef IOWA_DEVICE_RSC_HARDWARE_VERSION_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_HARDWARE_VERSION
#endif
#ifndef IOWA_DEVICE_RSC_SOFTWARE_VERSION_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_SOFTWARE_VERSION
#endif
#ifndef IOWA_DEVICE_RSC_MEMORY_TOTAL_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_MEMORY_TOTAL
#endif
#ifndef IOWA_DEVICE_RSC_MEMORY_FREE_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_MEMORY_FREE
#endif
#ifndef IOWA_DEVICE_RSC_EXTERNAL_INFO_REMOVE
#define IOWA_DEVICE_SUPPORT_RSC_EXTERNAL_INFO
#endif

// Check that IOWA_SERVER_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_SERVER_SUPPORT_RSC_DISABLE_TIMEOUT
#error "IOWA_SERVER_SUPPORT_RSC_DISABLE_TIMEOUT can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_SERVER_SUPPORT_RSC_DEFAULT_PERIODS
#error "IOWA_SERVER_SUPPORT_RSC_DEFAULT_PERIODS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_SERVER_SUPPORT_RSC_REGISTRATION_BEHAVIOUR
#error "IOWA_SERVER_SUPPORT_RSC_REGISTRATION_BEHAVIOUR can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_SERVER_SUPPORT_RSC_COMMUNICATION_ATTEMPTS
#error "IOWA_SERVER_SUPPORT_RSC_COMMUNICATION_ATTEMPTS can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_SERVER_SUPPORT_RSC_BOOTSTRAP_TRIGGER
#error "IOWA_SERVER_SUPPORT_RSC_BOOTSTRAP_TRIGGER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_SERVER_SUPPORT_RSC_MUTE_SEND
#error "IOWA_SERVER_SUPPORT_RSC_MUTE_SEND can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on Server Object.
#ifndef IOWA_SERVER_RSC_DISABLE_TIMEOUT_REMOVE
#define IOWA_SERVER_SUPPORT_RSC_DISABLE_TIMEOUT
#endif
#ifndef IOWA_SERVER_RSC_DEFAULT_PERIODS_REMOVE
#define IOWA_SERVER_SUPPORT_RSC_DEFAULT_PERIODS
/* Only relevant when LWM2M_VERSION_1_1_SUPPORT is set */
#endif

// Check that IOWA_LIGHT_CONTROL_SUPPORT_RSC_XX are not used with IOWA_REMOVE_ALL_OPTIONAL_RESOURCES not enabled.
#ifdef IOWA_LIGHT_CONTROL_SUPPORT_RSC_DIMMER
#error "IOWA_LIGHT_CONTROL_SUPPORT_RSC_DIMMER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_LIGHT_CONTROL_SUPPORT_RSC_ON_TIME
#error "IOWA_LIGHT_CONTROL_SUPPORT_RSC_ON_TIME can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_LIGHT_CONTROL_SUPPORT_RSC_CUMULATIVE_ACTIVE_POWER
#error "IOWA_LIGHT_CONTROL_SUPPORT_RSC_CUMULATIVE_ACTIVE_POWER can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_LIGHT_CONTROL_SUPPORT_RSC_POWER_FACTOR
#error "IOWA_LIGHT_CONTROL_SUPPORT_RSC_POWER_FACTOR can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif
#ifdef IOWA_LIGHT_CONTROL_SUPPORT_RSC_COLOUR
#error "IOWA_LIGHT_CONTROL_SUPPORT_RSC_COLOUR can only be enable if IOWA_REMOVE_ALL_OPTIONAL_RESOURCES is enabled."
#endif

// To enable resources on Light Control Object.
#ifndef IOWA_LIGHT_CONTROL_RSC_DIMMER_REMOVE
#define IOWA_LIGHT_CONTROL_SUPPORT_RSC_DIMMER
#endif
#ifndef IOWA_LIGHT_CONTROL_RSC_ON_TIME_REMOVE
#define IOWA_LIGHT_CONTROL_SUPPORT_RSC_ON_TIME
#endif
#ifndef IOWA_LIGHT_CONTROL_RSC_CUMULATIVE_ACTIVE_POWER_REMOVE
#define IOWA_LIGHT_CONTROL_SUPPORT_RSC_CUMULATIVE_ACTIVE_POWER
#endif
#ifndef IOWA_LIGHT_CONTROL_RSC_POWER_FACTOR_REMOVE
#define IOWA_LIGHT_CONTROL_SUPPORT_RSC_POWER_FACTOR
#endif
#ifndef IOWA_LIGHT_CONTROL_RSC_COLOUR_REMOVE
#define IOWA_LIGHT_CONTROL_SUPPORT_RSC_COLOUR
#endif

#endif // _IOWA_PRV_CORE_BACKWARD_COMPATIBILITY_CONFIG_
