/**********************************************
*
*  _________ _________ ___________ _________
* |         |         |   |   |   |         |
* |_________|         |   |   |   |    _    |
* |         |    |    |   |   |   |         |
* |         |    |    |           |         |
* |         |    |    |           |    |    |
* |         |         |           |    |    |
* |_________|_________|___________|____|____|
*
* Copyright (c) 2016-2020 IoTerop.
* All rights reserved.
*
* This program and the accompanying materials
* are made available under the terms of
* IoTerop’s IOWA License (LICENSE.TXT) which
* accompany this distribution.
*
**********************************************/

#ifndef _IOWA_LWM2M_ID_INCLUDE_
#define _IOWA_LWM2M_ID_INCLUDE_

#ifdef __cplusplus
extern "C" {
#endif

#define IOWA_LWM2M_REUSABLE_RESOURCE_ID_RANGE_START 2048
#define IOWA_LWM2M_REUSABLE_RESOURCE_ID_RANGE_END   26240

/******************
 * Security Object
 */

#define IOWA_LWM2M_SECURITY_OBJECT_ID 0

#define IOWA_LWM2M_SECURITY_ID_URI               0
#define IOWA_LWM2M_SECURITY_ID_BOOTSTRAP         1
#define IOWA_LWM2M_SECURITY_ID_SECURITY          2
#define IOWA_LWM2M_SECURITY_ID_PUBLIC_KEY        3
#define IOWA_LWM2M_SECURITY_ID_SERVER_PUBLIC_KEY 4
#define IOWA_LWM2M_SECURITY_ID_SECRET_KEY        5
#define IOWA_LWM2M_SECURITY_ID_SMS_SECURITY      6
#define IOWA_LWM2M_SECURITY_ID_SMS_KEY_PARAM     7
#define IOWA_LWM2M_SECURITY_ID_SMS_SECRET_KEY    8
#define IOWA_LWM2M_SECURITY_ID_SMS_SERVER_NUMBER 9
#define IOWA_LWM2M_SECURITY_ID_SHORT_SERVER_ID   10
#define IOWA_LWM2M_SECURITY_ID_HOLD_OFF          11
#define IOWA_LWM2M_SECURITY_ID_BOOTSTRAP_TIMEOUT 12
#define IOWA_LWM2M_SECURITY_ID_MATCHING_TYPE     13
#define IOWA_LWM2M_SECURITY_ID_SNI               14
#define IOWA_LWM2M_SECURITY_ID_CERTIFICATE_USAGE 15
#define IOWA_LWM2M_SECURITY_ID_CIPHERSUITE       16
#define IOWA_LWM2M_SECURITY_ID_OSCORE_SEC_MODE   17

#define IOWA_LWM2M_SECURITY_TYPE_URI               IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SECURITY_TYPE_BOOTSTRAP         IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SECURITY_TYPE_SECURITY          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_PUBLIC_KEY        IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SECURITY_TYPE_SERVER_PUBLIC_KEY IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SECURITY_TYPE_SECRET_KEY        IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SECURITY_TYPE_SMS_SECURITY      IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_SMS_KEY_PARAM     IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SECURITY_TYPE_SMS_SECRET_KEY    IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SECURITY_TYPE_SMS_SERVER_NUMBER IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SECURITY_TYPE_SHORT_SERVER_ID   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_HOLD_OFF          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_BOOTSTRAP_TIMEOUT IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_MATCHING_TYPE     IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_SNI               IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SECURITY_TYPE_CERTIFICATE_USAGE IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_CIPHERSUITE       IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SECURITY_TYPE_OSCORE_SEC_MODE   IOWA_LWM2M_TYPE_OBJECT_LINK

#define IOWA_LWM2M_SECURITY_OP_URI               IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_BOOTSTRAP         IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SECURITY          IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_PUBLIC_KEY        IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SERVER_PUBLIC_KEY IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SECRET_KEY        IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SMS_SECURITY      IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SMS_KEY_PARAM     IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SMS_SECRET_KEY    IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SMS_SERVER_NUMBER IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SHORT_SERVER_ID   IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_HOLD_OFF          IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_BOOTSTRAP_TIMEOUT IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_MATCHING_TYPE     IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_SNI               IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_CERTIFICATE_USAGE IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_CIPHERSUITE       IOWA_OPERATION_NONE
#define IOWA_LWM2M_SECURITY_OP_OSCORE_SEC_MODE   IOWA_OPERATION_NONE

#define IOWA_LWM2M_SECURITY_FLAGS_URI               IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SECURITY_FLAGS_BOOTSTRAP         IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SECURITY_FLAGS_SECURITY          IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SECURITY_FLAGS_PUBLIC_KEY        IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SECURITY_FLAGS_SERVER_PUBLIC_KEY IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SECURITY_FLAGS_SECRET_KEY        IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SECURITY_FLAGS_SMS_SECURITY      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_SMS_KEY_PARAM     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_SMS_SECRET_KEY    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_SMS_SERVER_NUMBER IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_SHORT_SERVER_ID   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_HOLD_OFF          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_BOOTSTRAP_TIMEOUT IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_MATCHING_TYPE     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_SNI               IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_CERTIFICATE_USAGE IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_CIPHERSUITE       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SECURITY_FLAGS_OSCORE_SEC_MODE   IOWA_RESOURCE_FLAG_OPTIONAL

/****************
 * Server Object
 */

#define IOWA_LWM2M_SERVER_OBJECT_ID 1

#define IOWA_LWM2M_SERVER_ID_SHORT_ID            0
#define IOWA_LWM2M_SERVER_ID_LIFETIME            1
#define IOWA_LWM2M_SERVER_ID_MIN_PERIOD          2
#define IOWA_LWM2M_SERVER_ID_MAX_PERIOD          3
#define IOWA_LWM2M_SERVER_ID_DISABLE             4
#define IOWA_LWM2M_SERVER_ID_TIMEOUT             5
#define IOWA_LWM2M_SERVER_ID_STORING             6
#define IOWA_LWM2M_SERVER_ID_BINDING             7
#define IOWA_LWM2M_SERVER_ID_UPDATE              8
#define IOWA_LWM2M_SERVER_ID_BOOTSTRAP_TRIGGER   9
#define IOWA_LWM2M_SERVER_ID_APN_LINK            10
#define IOWA_LWM2M_SERVER_ID_TLS_DTLS_ALERT      11
#define IOWA_LWM2M_SERVER_ID_LAST_BOOTSTRAP      12
#define IOWA_LWM2M_SERVER_ID_PRIORITY            13
#define IOWA_LWM2M_SERVER_ID_INITIAL_DELAY       14
#define IOWA_LWM2M_SERVER_ID_REG_FAIL_BLOCK      15
#define IOWA_LWM2M_SERVER_ID_BOOTSTRAP_REG_FAIL  16
#define IOWA_LWM2M_SERVER_ID_COMM_RETRY_COUNT    17
#define IOWA_LWM2M_SERVER_ID_COMM_RETRY_TIMER    18
#define IOWA_LWM2M_SERVER_ID_COMM_SEQUENCE_DELAY 19
#define IOWA_LWM2M_SERVER_ID_COMM_SEQUENCE_COUNT 20
#define IOWA_LWM2M_SERVER_ID_TRIGGER             21
#define IOWA_LWM2M_SERVER_ID_PREF_TRANSPORT      22
#define IOWA_LWM2M_SERVER_ID_MUTE_SEND           23

#define IOWA_LWM2M_SERVER_TYPE_SHORT_ID            IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_LIFETIME            IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_MIN_PERIOD          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_MAX_PERIOD          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_DISABLE             IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SERVER_TYPE_TIMEOUT             IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_STORING             IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SERVER_TYPE_BINDING             IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SERVER_TYPE_UPDATE              IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SERVER_TYPE_BOOTSTRAP_TRIGGER   IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SERVER_TYPE_APN_LINK            IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_SERVER_TYPE_TLS_DTLS_ALERT      IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_LAST_BOOTSTRAP      IOWA_LWM2M_TYPE_TIME
#define IOWA_LWM2M_SERVER_TYPE_PRIORITY            IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_INITIAL_DELAY       IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_REG_FAIL_BLOCK      IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SERVER_TYPE_BOOTSTRAP_REG_FAIL  IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SERVER_TYPE_COMM_RETRY_COUNT    IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_COMM_RETRY_TIMER    IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_COMM_SEQUENCE_DELAY IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_COMM_SEQUENCE_COUNT IOWA_LWM2M_TYPE_UNSIGNED_INTEGER
#define IOWA_LWM2M_SERVER_TYPE_TRIGGER             IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SERVER_TYPE_PREF_TRANSPORT      IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SERVER_TYPE_MUTE_SEND           IOWA_LWM2M_TYPE_BOOLEAN

#define IOWA_LWM2M_SERVER_OP_SHORT_ID            IOWA_OPERATION_READ
#define IOWA_LWM2M_SERVER_OP_LIFETIME            (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_MIN_PERIOD          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_MAX_PERIOD          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_DISABLE             IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SERVER_OP_TIMEOUT             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_STORING             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_BINDING             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_UPDATE              IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SERVER_OP_BOOTSTRAP_TRIGGER   IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SERVER_OP_APN_LINK            (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_TLS_DTLS_ALERT      IOWA_OPERATION_READ
#define IOWA_LWM2M_SERVER_OP_LAST_BOOTSTRAP      IOWA_OPERATION_READ
#define IOWA_LWM2M_SERVER_OP_PRIORITY            IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_INITIAL_DELAY       IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_REG_FAIL_BLOCK      IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_BOOTSTRAP_REG_FAIL  IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_COMM_RETRY_COUNT    IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_COMM_RETRY_TIMER    IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_COMM_SEQUENCE_DELAY IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_COMM_SEQUENCE_COUNT IOWA_OPERATION_NONE
#define IOWA_LWM2M_SERVER_OP_TRIGGER             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_PREF_TRANSPORT      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SERVER_OP_MUTE_SEND           (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_SERVER_FLAGS_SHORT_ID            IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SERVER_FLAGS_LIFETIME            IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SERVER_FLAGS_MIN_PERIOD          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_MAX_PERIOD          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_DISABLE             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_TIMEOUT             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_STORING             IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SERVER_FLAGS_BINDING             IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SERVER_FLAGS_UPDATE              IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SERVER_FLAGS_BOOTSTRAP_TRIGGER   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_APN_LINK            IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_TLS_DTLS_ALERT      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_LAST_BOOTSTRAP      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_PRIORITY            IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_INITIAL_DELAY       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_REG_FAIL_BLOCK      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_BOOTSTRAP_REG_FAIL  IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_COMM_RETRY_COUNT    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_COMM_RETRY_TIMER    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_COMM_SEQUENCE_DELAY IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_COMM_SEQUENCE_COUNT IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_TRIGGER             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_PREF_TRANSPORT      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SERVER_FLAGS_MUTE_SEND           IOWA_RESOURCE_FLAG_OPTIONAL

/************************
 * Access Control Object
 */

#define IOWA_LWM2M_ACCESS_CONTROL_LIST_OBJECT_ID 2

#define IOWA_LWM2M_ACCESS_CONTROL_LIST_ID_OBJECT_ID   0
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_ID_INSTANCE_ID 1
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_ID_ACL         2
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_ID_OWNER       3

#define IOWA_LWM2M_ACCESS_CONTROL_LIST_TYPE_OBJECT_ID   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_TYPE_INSTANCE_ID IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_TYPE_ACL         IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_TYPE_OWNER       IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_ACCESS_CONTROL_LIST_OP_OBJECT_ID   IOWA_OPERATION_READ
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_OP_INSTANCE_ID IOWA_OPERATION_READ
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_OP_ACL         (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_OP_OWNER       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_ACCESS_CONTROL_LIST_FLAGS_OBJECT_ID   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_FLAGS_INSTANCE_ID IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_FLAGS_ACL         (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_ACCESS_CONTROL_LIST_FLAGS_OWNER       IOWA_RESOURCE_FLAG_MANDATORY

/****************
 * Device Object
 */

#define IOWA_LWM2M_DEVICE_OBJECT_ID 3

#define IOWA_LWM2M_DEVICE_ID_MANUFACTURER        0
#define IOWA_LWM2M_DEVICE_ID_MODEL_NUMBER        1
#define IOWA_LWM2M_DEVICE_ID_SERIAL_NUMBER       2
#define IOWA_LWM2M_DEVICE_ID_FIRMWARE_VERSION    3
#define IOWA_LWM2M_DEVICE_ID_REBOOT              4
#define IOWA_LWM2M_DEVICE_ID_FACTORY_RESET       5
#define IOWA_LWM2M_DEVICE_ID_AVAILABLE_POWER_SRC 6
#define IOWA_LWM2M_DEVICE_ID_POWER_SRC_VOLTAGE   7
#define IOWA_LWM2M_DEVICE_ID_POWER_SRC_CURRENT   8
#define IOWA_LWM2M_DEVICE_ID_BATTERY_LEVEL       9
#define IOWA_LWM2M_DEVICE_ID_MEMORY_FREE         10
#define IOWA_LWM2M_DEVICE_ID_ERROR_CODE          11
#define IOWA_LWM2M_DEVICE_ID_RESET_ERROR         12
#define IOWA_LWM2M_DEVICE_ID_CURRENT_TIME        13
#define IOWA_LWM2M_DEVICE_ID_UTC_OFFSET          14
#define IOWA_LWM2M_DEVICE_ID_TIME_ZONE           15
#define IOWA_LWM2M_DEVICE_ID_BINDING             16
#define IOWA_LWM2M_DEVICE_ID_TYPE                17
#define IOWA_LWM2M_DEVICE_ID_HARDWARE_VERSION    18
#define IOWA_LWM2M_DEVICE_ID_SOFTWARE_VERSION    19
#define IOWA_LWM2M_DEVICE_ID_BATTERY_STATUS      20
#define IOWA_LWM2M_DEVICE_ID_MEMORY_TOTAL        21
#define IOWA_LWM2M_DEVICE_ID_EXT_DEV_INFO        22

#define IOWA_LWM2M_DEVICE_TYPE_MANUFACTURER        IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_MODEL_NUMBER        IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_SERIAL_NUMBER       IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_FIRMWARE_VERSION    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_REBOOT              IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_DEVICE_TYPE_FACTORY_RESET       IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_DEVICE_TYPE_AVAILABLE_POWER_SRC IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_POWER_SRC_VOLTAGE   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_POWER_SRC_CURRENT   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_BATTERY_LEVEL       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_MEMORY_FREE         IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_ERROR_CODE          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_RESET_ERROR         IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_DEVICE_TYPE_CURRENT_TIME        IOWA_LWM2M_TYPE_TIME
#define IOWA_LWM2M_DEVICE_TYPE_UTC_OFFSET          IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_TIME_ZONE           IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_BINDING             IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_TYPE                IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_HARDWARE_VERSION    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_SOFTWARE_VERSION    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEVICE_TYPE_BATTERY_STATUS      IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_MEMORY_TOTAL        IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEVICE_TYPE_EXT_DEV_INFO        IOWA_LWM2M_TYPE_OBJECT_LINK

#define IOWA_LWM2M_DEVICE_OP_MANUFACTURER        IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_MODEL_NUMBER        IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_SERIAL_NUMBER       IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_FIRMWARE_VERSION    IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_REBOOT              IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_DEVICE_OP_FACTORY_RESET       IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_DEVICE_OP_AVAILABLE_POWER_SRC IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_POWER_SRC_VOLTAGE   IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_POWER_SRC_CURRENT   IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_BATTERY_LEVEL       IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_MEMORY_FREE         IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_ERROR_CODE          IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_RESET_ERROR         IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_DEVICE_OP_CURRENT_TIME        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_DEVICE_OP_UTC_OFFSET          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_DEVICE_OP_TIME_ZONE           (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_DEVICE_OP_BINDING             IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_TYPE                IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_HARDWARE_VERSION    IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_SOFTWARE_VERSION    IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_BATTERY_STATUS      IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_MEMORY_TOTAL        IOWA_OPERATION_READ
#define IOWA_LWM2M_DEVICE_OP_EXT_DEV_INFO        IOWA_OPERATION_READ

#define IOWA_LWM2M_DEVICE_FLAGS_MANUFACTURER        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_MODEL_NUMBER        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_SERIAL_NUMBER       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_FIRMWARE_VERSION    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_REBOOT              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_FACTORY_RESET       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_AVAILABLE_POWER_SRC (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_DEVICE_FLAGS_POWER_SRC_VOLTAGE   (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_DEVICE_FLAGS_POWER_SRC_CURRENT   (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_DEVICE_FLAGS_BATTERY_LEVEL       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_MEMORY_FREE         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_ERROR_CODE          (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_DEVICE_FLAGS_RESET_ERROR         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_CURRENT_TIME        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_UTC_OFFSET          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_TIME_ZONE           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_BINDING             IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_DEVICE_FLAGS_TYPE                IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_HARDWARE_VERSION    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_SOFTWARE_VERSION    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_BATTERY_STATUS      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_MEMORY_TOTAL        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEVICE_FLAGS_EXT_DEV_INFO        (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)

/*********************************
 * Connectivity Monitoring Object
 */

#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OBJECT_ID 4

#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_BEARER           0
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_AVAILABLE_BEARER 1
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_SIGNAL_STRENGTH  2
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_LINK_QUALITY     3
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_IP_ADDR          4
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_ROUTER_IP_ADDR   5
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_LINK_USAGE       6
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_APN              7
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_CELL_ID          8
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_SMNC             9
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_SMCC             10
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_SINR             11
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_ID_LAC              12

#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_BEARER           IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_AVAILABLE_BEARER IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_SIGNAL_STRENGTH  IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_LINK_QUALITY     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_IP_ADDR          IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_ROUTER_IP_ADDR   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_LINK_USAGE       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_APN              IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_CELL_ID          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_SMNC             IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_SMCC             IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_SINR             IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_TYPE_LAC              IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_BEARER           IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_AVAILABLE_BEARER IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_SIGNAL_STRENGTH  IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_LINK_QUALITY     IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_IP_ADDR          IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_ROUTER_IP_ADDR   IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_LINK_USAGE       IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_APN              IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_CELL_ID          IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_SMNC             IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_SMCC             IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_SINR             IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_OP_LAC              IOWA_OPERATION_READ

#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_BEARER           IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_AVAILABLE_BEARER (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_SIGNAL_STRENGTH  IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_LINK_QUALITY     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_IP_ADDR          (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_ROUTER_IP_ADDR   (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_LINK_USAGE       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_APN              (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_CELL_ID          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_SMNC             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_SMCC             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_SINR             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_MONITORING_FLAGS_LAC              IOWA_RESOURCE_FLAG_OPTIONAL

/*************************
 * Firmware Update Object
 */

#define IOWA_LWM2M_FIRMWARE_OBJECT_ID 5

#define IOWA_LWM2M_FIRMWARE_ID_PACKAGE         0
#define IOWA_LWM2M_FIRMWARE_ID_PACKAGE_URI     1
#define IOWA_LWM2M_FIRMWARE_ID_UPDATE          2
#define IOWA_LWM2M_FIRMWARE_ID_STATE           3
#define IOWA_LWM2M_FIRMWARE_ID_UPDATE_RESULT   5
#define IOWA_LWM2M_FIRMWARE_ID_PACKAGE_NAME    6
#define IOWA_LWM2M_FIRMWARE_ID_PACKAGE_VERSION 7
#define IOWA_LWM2M_FIRMWARE_ID_PROTOCOL        8
#define IOWA_LWM2M_FIRMWARE_ID_DELIVERY_METHOD 9

#define IOWA_LWM2M_FIRMWARE_TYPE_PACKAGE         IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_FIRMWARE_TYPE_PACKAGE_URI     IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_FIRMWARE_TYPE_UPDATE          IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_FIRMWARE_TYPE_STATE           IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_FIRMWARE_TYPE_UPDATE_RESULT   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_FIRMWARE_TYPE_PACKAGE_NAME    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_FIRMWARE_TYPE_PACKAGE_VERSION IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_FIRMWARE_TYPE_PROTOCOL        IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_FIRMWARE_TYPE_DELIVERY_METHOD IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_FIRMWARE_OP_PACKAGE         IOWA_OPERATION_WRITE
#define IOWA_LWM2M_FIRMWARE_OP_PACKAGE_URI     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_FIRMWARE_OP_UPDATE          IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_FIRMWARE_OP_STATE           IOWA_OPERATION_READ
#define IOWA_LWM2M_FIRMWARE_OP_UPDATE_RESULT   IOWA_OPERATION_READ
#define IOWA_LWM2M_FIRMWARE_OP_PACKAGE_NAME    IOWA_OPERATION_READ
#define IOWA_LWM2M_FIRMWARE_OP_PACKAGE_VERSION IOWA_OPERATION_READ
#define IOWA_LWM2M_FIRMWARE_OP_PROTOCOL        IOWA_OPERATION_READ
#define IOWA_LWM2M_FIRMWARE_OP_DELIVERY_METHOD IOWA_OPERATION_READ

#define IOWA_LWM2M_FIRMWARE_FLAGS_PACKAGE         IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_FIRMWARE_FLAGS_PACKAGE_URI     IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_FIRMWARE_FLAGS_UPDATE          IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_FIRMWARE_FLAGS_STATE           IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_FIRMWARE_FLAGS_UPDATE_RESULT   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_FIRMWARE_FLAGS_PACKAGE_NAME    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_FIRMWARE_FLAGS_PACKAGE_VERSION IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_FIRMWARE_FLAGS_PROTOCOL        (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_FIRMWARE_FLAGS_DELIVERY_METHOD IOWA_RESOURCE_FLAG_MANDATORY

#define IOWA_LWM2M_FIRMWARE_VALUE_PROTOCOL_COAP      0
#define IOWA_LWM2M_FIRMWARE_VALUE_PROTOCOL_COAPS     1
#define IOWA_LWM2M_FIRMWARE_VALUE_PROTOCOL_HTTP      2
#define IOWA_LWM2M_FIRMWARE_VALUE_PROTOCOL_HTTPS     3
#define IOWA_LWM2M_FIRMWARE_VALUE_PROTOCOL_COAP_TCP  4
#define IOWA_LWM2M_FIRMWARE_VALUE_PROTOCOL_COAP_TLS  5

/******************
 * Location Object
 */

#define IOWA_LWM2M_LOCATION_OBJECT_ID 6

#define IOWA_LWM2M_LOCATION_ID_LATITUDE  0
#define IOWA_LWM2M_LOCATION_ID_LONGITUDE 1
#define IOWA_LWM2M_LOCATION_ID_ALTITUDE  2
#define IOWA_LWM2M_LOCATION_ID_RADIUS    3
#define IOWA_LWM2M_LOCATION_ID_VELOCITY  4
#define IOWA_LWM2M_LOCATION_ID_TIMESTAMP 5
#define IOWA_LWM2M_LOCATION_ID_SPEED     6

#define IOWA_LWM2M_LOCATION_TYPE_LATITUDE  IOWA_LWM2M_TYPE_FLOAT
#define IOWA_LWM2M_LOCATION_TYPE_LONGITUDE IOWA_LWM2M_TYPE_FLOAT
#define IOWA_LWM2M_LOCATION_TYPE_ALTITUDE  IOWA_LWM2M_TYPE_FLOAT
#define IOWA_LWM2M_LOCATION_TYPE_RADIUS    IOWA_LWM2M_TYPE_FLOAT
#define IOWA_LWM2M_LOCATION_TYPE_VELOCITY  IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_LOCATION_TYPE_TIMESTAMP IOWA_LWM2M_TYPE_TIME
#define IOWA_LWM2M_LOCATION_TYPE_SPEED     IOWA_LWM2M_TYPE_FLOAT

#define IOWA_LWM2M_LOCATION_OP_LATITUDE  IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCATION_OP_LONGITUDE IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCATION_OP_ALTITUDE  IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCATION_OP_RADIUS    IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCATION_OP_VELOCITY  IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCATION_OP_TIMESTAMP IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCATION_OP_SPEED     IOWA_OPERATION_READ

#define IOWA_LWM2M_LOCATION_FLAGS_LATITUDE  IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_LOCATION_FLAGS_LONGITUDE IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_LOCATION_FLAGS_ALTITUDE  IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_LOCATION_FLAGS_RADIUS    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_LOCATION_FLAGS_VELOCITY  IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_LOCATION_FLAGS_TIMESTAMP IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_LOCATION_FLAGS_SPEED     IOWA_RESOURCE_FLAG_OPTIONAL

/*********************************
 * Connectivity Statistics Object
 */

#define IOWA_LWM2M_CONNECTIVITY_STATS_OBJECT_ID 7

#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_SMS_TX_COUNTER       0
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_SMS_RX_COUNTER       1
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_TX_DATA              2
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_RX_DATA              3
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_MAX_MESSAGE_SIZE     4
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_AVERAGE_MESSAGE_SIZE 5
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_START                6
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_STOP                 7
#define IOWA_LWM2M_CONNECTIVITY_STATS_ID_COLLECTION_PERIOD    8

#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_SMS_TX_COUNTER       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_SMS_RX_COUNTER       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_TX_DATA              IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_RX_DATA              IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_MAX_MESSAGE_SIZE     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_AVERAGE_MESSAGE_SIZE IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_START                IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_STOP                 IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_CONNECTIVITY_STATS_TYPE_COLLECTION_PERIOD    IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_SMS_TX_COUNTER       IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_SMS_RX_COUNTER       IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_TX_DATA              IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_RX_DATA              IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_MAX_MESSAGE_SIZE     IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_AVERAGE_MESSAGE_SIZE IOWA_OPERATION_READ
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_START                IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_STOP                 IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_CONNECTIVITY_STATS_OP_COLLECTION_PERIOD    (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_SMS_TX_COUNTER       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_SMS_RX_COUNTER       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_TX_DATA              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_RX_DATA              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_MAX_MESSAGE_SIZE     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_AVERAGE_MESSAGE_SIZE IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_START                IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_STOP                 IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_CONNECTIVITY_STATS_FLAGS_COLLECTION_PERIOD    IOWA_RESOURCE_FLAG_OPTIONAL

/**********************
 * Lock and Wipe Object
 */

#define IOWA_LWM2M_LOCK_AND_WIPE_OBJECT_ID 8

#define IOWA_LWM2M_LOCK_AND_WIPE_ID_STATE       0
#define IOWA_LWM2M_LOCK_AND_WIPE_ID_LOCK_TARGET 1
#define IOWA_LWM2M_LOCK_AND_WIPE_ID_WIPE_ITEM   2
#define IOWA_LWM2M_LOCK_AND_WIPE_ID_WIPE        3
#define IOWA_LWM2M_LOCK_AND_WIPE_ID_WIPE_TARGET 4
#define IOWA_LWM2M_LOCK_AND_WIPE_ID_OP_RESULT   5

#define IOWA_LWM2M_LOCK_AND_WIPE_TYPE_STATE       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_LOCK_AND_WIPE_TYPE_LOCK_TARGET IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_LOCK_AND_WIPE_TYPE_WIPE_ITEM   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_LOCK_AND_WIPE_TYPE_WIPE        IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_LOCK_AND_WIPE_TYPE_WIPE_TARGET IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_LOCK_AND_WIPE_TYPE_OP_RESULT   IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_LOCK_AND_WIPE_OP_STATE       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_LOCK_AND_WIPE_OP_LOCK_TARGET IOWA_OPERATION_WRITE
#define IOWA_LWM2M_LOCK_AND_WIPE_OP_WIPE_ITEM   IOWA_OPERATION_READ
#define IOWA_LWM2M_LOCK_AND_WIPE_OP_WIPE        IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_LOCK_AND_WIPE_OP_WIPE_TARGET IOWA_OPERATION_WRITE
#define IOWA_LWM2M_LOCK_AND_WIPE_OP_OP_RESULT   IOWA_OPERATION_READ

#define IOWA_LWM2M_LOCK_AND_WIPE_FLAGS_STATE       IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_LOCK_AND_WIPE_FLAGS_LOCK_TARGET (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_LOCK_AND_WIPE_FLAGS_WIPE_ITEM   (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_LOCK_AND_WIPE_FLAGS_WIPE        IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_LOCK_AND_WIPE_FLAGS_WIPE_TARGET (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_LOCK_AND_WIPE_FLAGS_OP_RESULT   IOWA_RESOURCE_FLAG_MANDATORY

/****************************
 * Software Management Object
 */

#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OBJECT_ID 9

#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_PACKAGE_NAME              0
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_PACKAGE_VERSION           1
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_PACKAGE                   2
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_PACKAGE_URI               3
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_INSTALL                   4
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_CHECKPOINT                5
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_UNINSTALL                 6
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_UPDATE_STATE              7
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_UPDATE_OBJECTS            8
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_UPDATE_RESULT             9
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_ACTIVATE                  10
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_DEACTIVATE                11
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_ACTIVATION_STATE          12
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_PACKAGE_SETTINGS          13
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_USERNAME                  14
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_PASSWORD                  15
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_STATUS_REASON             16
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_SW_COMPONENT_LINK         17
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_ID_SW_COMPONENT_TREE_LENGTH  18

#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_PACKAGE_NAME                IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_PACKAGE_VERSION             IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_PACKAGE                     IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_PACKAGE_URI                 IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_INSTALL                     IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_CHECKPOINT                  IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_UNINSTALL                   IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_UPDATE_STATE                IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_UPDATE_OBJECTS              IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_UPDATE_RESULT               IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_ACTIVATE                    IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_DEACTIVATE                  IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_ACTIVATION_STATE            IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_PACKAGE_SETTINGS            IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_USERNAME                    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_PASSWORD                    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_STATUS_REASON               IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_SW_COMPONENT_LINK           IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_TYPE_SW_COMPONENT_TREE_LENGTH    IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_PACKAGE_NAME              IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_PACKAGE_VERSION           IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_PACKAGE                   IOWA_OPERATION_WRITE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_PACKAGE_URI               IOWA_OPERATION_WRITE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_INSTALL                   IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_CHECKPOINT                IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_UNINSTALL                 IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_UPDATE_STATE              IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_UPDATE_OBJECTS            (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_UPDATE_RESULT             IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_ACTIVATE                  IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_DEACTIVATE                IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_ACTIVATION_STATE          IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_PACKAGE_SETTINGS          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_USERNAME                  IOWA_OPERATION_WRITE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_PASSWORD                  IOWA_OPERATION_WRITE
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_STATUS_REASON             IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_SW_COMPONENT_LINK         IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_OP_SW_COMPONENT_TREE_LENGTH  IOWA_OPERATION_READ

#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_PACKAGE_NAME               IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_PACKAGE_VERSION            IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_PACKAGE                    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_PACKAGE_URI                IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_INSTALL                    IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_CHECKPOINT                 IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_UNINSTALL                  IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_UPDATE_STATE               IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_UPDATE_OBJECTS             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_UPDATE_RESULT              IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_ACTIVATE                   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_DEACTIVATE                 IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_ACTIVATION_STATE           IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_PACKAGE_SETTINGS           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_USERNAME                   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_PASSWORD                   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_STATUS_REASON              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_SW_COMPONENT_LINK          (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_SOFTWARE_MANAGEMENT_FLAGS_SW_COMPONENT_TREE_LENGTH   IOWA_RESOURCE_FLAG_OPTIONAL

/*******************************
 * Cellular Connectivity Object
 */

#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OBJECT_ID 10

#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_SMSC_ADDRESS           0
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_DISABLE_RADIO_PERIOD   1
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_MODULE_ACTIVATION_CODE 2
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_VENDOR_SPECIFIC_EXT    3
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_PSM_TIMER              4
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_ACTIVE_TIMER           5
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_PLMN_RATE_CONTROL      6
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_EDRX_PARAM_IU_MODE     7
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_EDRX_PARAM_WB_S1_MODE  8
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_EDRX_PARAM_NB_S1_MODE  9
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_EDRX_PARAM_A_GB_MODE   10
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_ID_ACTIVATED_PROFILE_NAME 11

#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_SMSC_ADDRESS           IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_DISABLE_RADIO_PERIOD   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_MODULE_ACTIVATION_CODE IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_VENDOR_SPECIFIC_EXT    IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_PSM_TIMER              IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_ACTIVE_TIMER           IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_PLMN_RATE_CONTROL      IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_EDRX_PARAM_IU_MODE     IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_EDRX_PARAM_WB_S1_MODE  IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_EDRX_PARAM_NB_S1_MODE  IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_EDRX_PARAM_A_GB_MODE   IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_TYPE_ACTIVATED_PROFILE_NAME IOWA_LWM2M_TYPE_OBJECT_LINK

#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_SMSC_ADDRESS           (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_DISABLE_RADIO_PERIOD   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_MODULE_ACTIVATION_CODE (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_VENDOR_SPECIFIC_EXT    IOWA_OPERATION_READ
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_PSM_TIMER              (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_ACTIVE_TIMER           (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_PLMN_RATE_CONTROL      IOWA_OPERATION_READ
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_EDRX_PARAM_IU_MODE     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_EDRX_PARAM_WB_S1_MODE  (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_EDRX_PARAM_NB_S1_MODE  (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_EDRX_PARAM_A_GB_MODE   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_OP_ACTIVATED_PROFILE_NAME IOWA_OPERATION_READ

#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_SMSC_ADDRESS           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_DISABLE_RADIO_PERIOD   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_MODULE_ACTIVATION_CODE IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_VENDOR_SPECIFIC_EXT    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_PSM_TIMER              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_ACTIVE_TIMER           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_PLMN_RATE_CONTROL      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_EDRX_PARAM_IU_MODE     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_EDRX_PARAM_WB_S1_MODE  IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_EDRX_PARAM_NB_S1_MODE  IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_EDRX_PARAM_A_GB_MODE   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_CELLULAR_CONNECTIVITY_FLAGS_ACTIVATED_PROFILE_NAME (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)

/*************
 * APN Object
 */

#define IOWA_LWM2M_APN_OBJECT_ID 11

#define IOWA_LWM2M_APN_ID_PROFILE_NAME                    0
#define IOWA_LWM2M_APN_ID_APN                             1
#define IOWA_LWM2M_APN_ID_AUTO_SELECT_APN_DEVICE          2
#define IOWA_LWM2M_APN_ID_ENABLE_STATUS                   3
#define IOWA_LWM2M_APN_ID_AUTHENTICATION_TYPE             4
#define IOWA_LWM2M_APN_ID_USER_NAME                       5
#define IOWA_LWM2M_APN_ID_SECRET                          6
#define IOWA_LWM2M_APN_ID_RECONNECT_SCHEDULE              7
#define IOWA_LWM2M_APN_ID_VALIDITY                        8
#define IOWA_LWM2M_APN_ID_CONN_ESTABLISHMENT_TIME         9
#define IOWA_LWM2M_APN_ID_CONN_ESTABLISHMENT_RESULT       10
#define IOWA_LWM2M_APN_ID_CONN_ESTABLISHMENT_REJECT_CAUSE 11
#define IOWA_LWM2M_APN_ID_CONNECTION_END_TIME             12
#define IOWA_LWM2M_APN_ID_TOTAL_BYTES_SENT                13
#define IOWA_LWM2M_APN_ID_TOTAL_BYTES_RECEIVED            14
#define IOWA_LWM2M_APN_ID_IP_ADDRESS                      15
#define IOWA_LWM2M_APN_ID_PREFIX_LENGTH                   16
#define IOWA_LWM2M_APN_ID_SUBNET_MASK                     17
#define IOWA_LWM2M_APN_ID_GATEWAY                         18
#define IOWA_LWM2M_APN_ID_PRIMARY_DNS_ADDRESS             19
#define IOWA_LWM2M_APN_ID_SECONDARY_DNS_ADDRESS           20
#define IOWA_LWM2M_APN_ID_QCI                             21
#define IOWA_LWM2M_APN_ID_VENDOR_SPECIFIC_EXT             22
#define IOWA_LWM2M_APN_ID_TOTAL_PACKETS_SENT              23
#define IOWA_LWM2M_APN_ID_PDN_TYPE                        24
#define IOWA_LWM2M_APN_ID_APN_RATE_CONTROL                25

#define IOWA_LWM2M_APN_TYPE_PROFILE_NAME                    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_APN                             IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_AUTO_SELECT_APN_DEVICE          IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_APN_TYPE_ENABLE_STATUS                   IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_APN_TYPE_AUTHENTICATION_TYPE             IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_USER_NAME                       IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_SECRET                          IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_RECONNECT_SCHEDULE              IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_VALIDITY                        IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_CONN_ESTABLISHMENT_TIME         IOWA_LWM2M_TYPE_TIME
#define IOWA_LWM2M_APN_TYPE_CONN_ESTABLISHMENT_RESULT       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_CONN_ESTABLISHMENT_REJECT_CAUSE IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_CONNECTION_END_TIME             IOWA_LWM2M_TYPE_TIME
#define IOWA_LWM2M_APN_TYPE_TOTAL_BYTES_SENT                IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_TOTAL_BYTES_RECEIVED            IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_IP_ADDRESS                      IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_PREFIX_LENGTH                   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_SUBNET_MASK                     IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_GATEWAY                         IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_PRIMARY_DNS_ADDRESS             IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_SECONDARY_DNS_ADDRESS           IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_APN_TYPE_QCI                             IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_VENDOR_SPECIFIC_EXT             IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_APN_TYPE_TOTAL_PACKETS_SENT              IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_PDN_TYPE                        IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_APN_TYPE_APN_RATE_CONTROL                IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_APN_OP_PROFILE_NAME                    (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_APN                             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_AUTO_SELECT_APN_DEVICE          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_ENABLE_STATUS                   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_AUTHENTICATION_TYPE             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_USER_NAME                       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_SECRET                          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_RECONNECT_SCHEDULE              (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_VALIDITY                        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_CONN_ESTABLISHMENT_TIME         IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_CONN_ESTABLISHMENT_RESULT       IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_CONN_ESTABLISHMENT_REJECT_CAUSE IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_CONNECTION_END_TIME             IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_TOTAL_BYTES_SENT                IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_TOTAL_BYTES_RECEIVED            IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_IP_ADDRESS                      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_PREFIX_LENGTH                   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_SUBNET_MASK                     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_GATEWAY                         (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_PRIMARY_DNS_ADDRESS             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_SECONDARY_DNS_ADDRESS           (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_QCI                             IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_VENDOR_SPECIFIC_EXT             IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_TOTAL_PACKETS_SENT              IOWA_OPERATION_READ
#define IOWA_LWM2M_APN_OP_PDN_TYPE                        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_APN_OP_APN_RATE_CONTROL                IOWA_OPERATION_READ

#define IOWA_LWM2M_APN_FLAGS_PROFILE_NAME                    IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_APN_FLAGS_APN                             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_AUTO_SELECT_APN_DEVICE          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_ENABLE_STATUS                   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_AUTHENTICATION_TYPE             IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_APN_FLAGS_USER_NAME                       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_SECRET                          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_RECONNECT_SCHEDULE              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_VALIDITY                        (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_CONN_ESTABLISHMENT_TIME         (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_CONN_ESTABLISHMENT_RESULT       (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_CONN_ESTABLISHMENT_REJECT_CAUSE (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_CONNECTION_END_TIME             (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_TOTAL_BYTES_SENT                IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_TOTAL_BYTES_RECEIVED            IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_IP_ADDRESS                      (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_PREFIX_LENGTH                   (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_SUBNET_MASK                     (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_GATEWAY                         (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_PRIMARY_DNS_ADDRESS             (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_SECONDARY_DNS_ADDRESS           (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_APN_FLAGS_QCI                             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_VENDOR_SPECIFIC_EXT             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_TOTAL_PACKETS_SENT              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_PDN_TYPE                        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_APN_FLAGS_APN_RATE_CONTROL                IOWA_RESOURCE_FLAG_OPTIONAL

/***************************
 * WLAN Connectivity Object
 */

#define IOWA_LWM2M_WLAN_CONNECTIVITY_OBJECT_ID 12

#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_INTERFACE_NAME         0
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_ENABLE                 1
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_RADIO_ENABLED          2
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_STATUS                 3
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_BSSID                  4
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_SSID                   5
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_BROADCAST_SSID         6
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_BEACON_ENABLED         7
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_MODE                   8
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_CHANNEL                9
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_AUTO_CHANNEL           10
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_SUPPORTED_CHANNELS     11
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_CHANNELS_IN_USE        12
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_REGULATORY_DOMAIN      13
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_STANDARD               14
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_AUTHENTICATION_MODE    15
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_ENCRYPTION_MODE        16
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WPA_PSK                17
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WPA_KEY_PHRASE         18
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_ENCRYPTION_TYPE    19
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_KEY_INDEX          20
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_KEY_PHRASE         21
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_KEY_1              22
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_KEY_2              23
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_KEY_3              24
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WEP_KEY_4              25
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_RADIUS_SERVER          26
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_RADIUS_SERVER_PORT     27
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_RADIUS_SECRET          28
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WMM_SUPPORTED          29
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_WMM_ENABLED            30
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_MAC_CONTROL_ENABLED    31
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_MAC_ADDRESS_LIST       32
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_TOTAL_BYTES_SENT       33
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_TOTAL_BYTES_RECEIVED   34
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_TOTAL_PACKETS_SENT     35
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_TOTAL_PACKETS_RECEIVED 36
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_TRANSMIT_ERRORS        37
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_RECEIVE_ERRORS         38
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_UNICAST_SENT           39
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_UNICAST_RECEIVED       40
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_MULTICAST_SENT         41
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_MULTICAST_RECEIVED     42
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_BROADCAST_SENT         43
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_BROADCAST_RECEIVED     44
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_DISCARD_SENT           45
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_DISCARD_RECEIVED       46
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_UNKNOWN_RECEIVED       47
#define IOWA_LWM2M_WLAN_CONNECTIVITY_ID_VENDOR_EXT             48

#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_INTERFACE_NAME         IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_ENABLE                 IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_RADIO_ENABLED          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_STATUS                 IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_BSSID                  IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_SSID                   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_BROADCAST_SSID         IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_BEACON_ENABLED         IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_MODE                   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_CHANNEL                IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_AUTO_CHANNEL           IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_SUPPORTED_CHANNELS     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_CHANNELS_IN_USE        IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_REGULATORY_DOMAIN      IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_STANDARD               IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_AUTHENTICATION_MODE    IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_ENCRYPTION_MODE        IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WPA_PSK                IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WPA_KEY_PHRASE         IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_ENCRYPTION_TYPE    IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_KEY_INDEX          IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_KEY_PHRASE         IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_KEY_1              IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_KEY_2              IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_KEY_3              IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WEP_KEY_4              IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_RADIUS_SERVER          IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_RADIUS_SERVER_PORT     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_RADIUS_SECRET          IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WMM_SUPPORTED          IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_WMM_ENABLED            IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_MAC_CONTROL_ENABLED    IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_MAC_ADDRESS_LIST       IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_TOTAL_BYTES_SENT       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_TOTAL_BYTES_RECEIVED   IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_TOTAL_PACKETS_SENT     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_TOTAL_PACKETS_RECEIVED IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_TRANSMIT_ERRORS        IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_RECEIVE_ERRORS         IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_UNICAST_SENT           IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_UNICAST_RECEIVED       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_MULTICAST_SENT         IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_MULTICAST_RECEIVED     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_BROADCAST_SENT         IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_BROADCAST_RECEIVED     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_DISCARD_SENT           IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_DISCARD_RECEIVED       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_UNKNOWN_RECEIVED       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_WLAN_CONNECTIVITY_TYPE_VENDOR_EXT             IOWA_LWM2M_TYPE_OBJECT_LINK

#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_INTERFACE_NAME         (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_ENABLE                 (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_RADIO_ENABLED          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_STATUS                 IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_BSSID                  IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_SSID                   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_BROADCAST_SSID         (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_BEACON_ENABLED         (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_MODE                   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_CHANNEL                (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_AUTO_CHANNEL           (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_SUPPORTED_CHANNELS     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_CHANNELS_IN_USE        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_REGULATORY_DOMAIN      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_STANDARD               (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_AUTHENTICATION_MODE    (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_ENCRYPTION_MODE        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WPA_PSK                IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WPA_KEY_PHRASE         IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_ENCRYPTION_TYPE    IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_KEY_INDEX          IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_KEY_PHRASE         IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_KEY_1              IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_KEY_2              IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_KEY_3              IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WEP_KEY_4              IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_RADIUS_SERVER          (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_RADIUS_SERVER_PORT     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_RADIUS_SECRET          IOWA_OPERATION_WRITE
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WMM_SUPPORTED          IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_WMM_ENABLED            (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_MAC_CONTROL_ENABLED    (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_MAC_ADDRESS_LIST       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_TOTAL_BYTES_SENT       IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_TOTAL_BYTES_RECEIVED   IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_TOTAL_PACKETS_SENT     IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_TOTAL_PACKETS_RECEIVED IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_TRANSMIT_ERRORS        IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_RECEIVE_ERRORS         IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_UNICAST_SENT           IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_UNICAST_RECEIVED       IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_MULTICAST_SENT         IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_MULTICAST_RECEIVED     IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_BROADCAST_SENT         IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_BROADCAST_RECEIVED     IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_DISCARD_SENT           IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_DISCARD_RECEIVED       IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_UNKNOWN_RECEIVED       IOWA_OPERATION_READ
#define IOWA_LWM2M_WLAN_CONNECTIVITY_OP_VENDOR_EXT             IOWA_OPERATION_READ

#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_INTERFACE_NAME         IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_ENABLE                 IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_RADIO_ENABLED          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_STATUS                 IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_BSSID                  IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_SSID                   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_BROADCAST_SSID         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_BEACON_ENABLED         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_MODE                   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_CHANNEL                IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_AUTO_CHANNEL           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_SUPPORTED_CHANNELS     (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_CHANNELS_IN_USE        (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_REGULATORY_DOMAIN      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_STANDARD               IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_AUTHENTICATION_MODE    IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_ENCRYPTION_MODE        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WPA_PSK                IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WPA_KEY_PHRASE         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_ENCRYPTION_TYPE    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_KEY_INDEX          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_KEY_PHRASE         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_KEY_1              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_KEY_2              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_KEY_3              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WEP_KEY_4              IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_RADIUS_SERVER          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_RADIUS_SERVER_PORT     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_RADIUS_SECRET          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WMM_SUPPORTED          IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_WMM_ENABLED            IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_MAC_CONTROL_ENABLED    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_MAC_ADDRESS_LIST       (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_TOTAL_BYTES_SENT       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_TOTAL_BYTES_RECEIVED   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_TOTAL_PACKETS_SENT     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_TOTAL_PACKETS_RECEIVED IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_TRANSMIT_ERRORS        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_RECEIVE_ERRORS         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_UNICAST_SENT           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_UNICAST_RECEIVED       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_MULTICAST_SENT         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_MULTICAST_RECEIVED     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_BROADCAST_SENT         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_BROADCAST_RECEIVED     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_DISCARD_SENT           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_DISCARD_RECEIVED       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_UNKNOWN_RECEIVED       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_WLAN_CONNECTIVITY_FLAGS_VENDOR_EXT             IOWA_RESOURCE_FLAG_OPTIONAL

/*************************
* Bearer Selection Object
*/

#define IOWA_LWM2M_BEARER_SELECTION_OBJECT_ID 13

#define IOWA_LWM2M_BEARER_SELECTION_ID_PREFERRED_COMM_BEARER     0
#define IOWA_LWM2M_BEARER_SELECTION_ID_ACCEPTABLE_RSSI_GSM       1
#define IOWA_LWM2M_BEARER_SELECTION_ID_ACCEPTABLE_RSCP_UMTS      2
#define IOWA_LWM2M_BEARER_SELECTION_ID_ACCEPTABLE_RSRP_LTE       3
#define IOWA_LWM2M_BEARER_SELECTION_ID_ACCEPTABLE_RSSI_EV_DO     4
#define IOWA_LWM2M_BEARER_SELECTION_ID_CELL_LOCK_LIST            5
#define IOWA_LWM2M_BEARER_SELECTION_ID_OPERATOR_LIST             6
#define IOWA_LWM2M_BEARER_SELECTION_ID_OPERATOR_LIST_MODE        7
#define IOWA_LWM2M_BEARER_SELECTION_ID_AVAILABLE_PLMNS           8
#define IOWA_LWM2M_BEARER_SELECTION_ID_VENDOR_SPECIFIC_EXT       9
#define IOWA_LWM2M_BEARER_SELECTION_ID_ACCEPTABLE_RSRP_NB_IOT    10
#define IOWA_LWM2M_BEARER_SELECTION_ID_PLMN_SEARCH_TIMER         11
#define IOWA_LWM2M_BEARER_SELECTION_ID_ATTACH_WO_PDN_CONNECTION  12

#define IOWA_LWM2M_BEARER_SELECTION_TYPE_PREFERRED_COMM_BEARER     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_ACCEPTABLE_RSSI_GSM       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_ACCEPTABLE_RSCP_UMTS      IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_ACCEPTABLE_RSRP_LTE       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_ACCEPTABLE_RSSI_EV_DO     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_CELL_LOCK_LIST            IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_OPERATOR_LIST             IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_OPERATOR_LIST_MODE        IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_AVAILABLE_PLMNS           IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_VENDOR_SPECIFIC_EXT       IOWA_LWM2M_TYPE_OBJECT_LINK
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_ACCEPTABLE_RSRP_NB_IOT    IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_PLMN_SEARCH_TIMER         IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BEARER_SELECTION_TYPE_ATTACH_WO_PDN_CONNECTION  IOWA_LWM2M_TYPE_BOOLEAN

#define IOWA_LWM2M_BEARER_SELECTION_OP_PREFERRED_COMM_BEARER     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_ACCEPTABLE_RSSI_GSM       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_ACCEPTABLE_RSCP_UMTS      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_ACCEPTABLE_RSRP_LTE       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_ACCEPTABLE_RSSI_EV_DO     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_CELL_LOCK_LIST            (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_OPERATOR_LIST             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_OPERATOR_LIST_MODE        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_AVAILABLE_PLMNS           IOWA_OPERATION_READ
#define IOWA_LWM2M_BEARER_SELECTION_OP_VENDOR_SPECIFIC_EXT       IOWA_OPERATION_READ
#define IOWA_LWM2M_BEARER_SELECTION_OP_ACCEPTABLE_RSRP_NB_IOT    (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_PLMN_SEARCH_TIMER         (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BEARER_SELECTION_OP_ATTACH_WO_PDN_CONNECTION  (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_PREFERRED_COMM_BEARER     (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_ACCEPTABLE_RSSI_GSM       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_ACCEPTABLE_RSCP_UMTS      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_ACCEPTABLE_RSRP_LTE       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_ACCEPTABLE_RSSI_EV_DO     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_CELL_LOCK_LIST            IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_OPERATOR_LIST             IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_OPERATOR_LIST_MODE        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_AVAILABLE_PLMNS           IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_VENDOR_SPECIFIC_EXT       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_ACCEPTABLE_RSRP_NB_IOT    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_PLMN_SEARCH_TIMER         IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BEARER_SELECTION_FLAGS_ATTACH_WO_PDN_CONNECTION  IOWA_RESOURCE_FLAG_OPTIONAL

/***************************
 * Software Component Object
 */

#define IOWA_LWM2M_SOFTWARE_COMPONENT_OBJECT_ID 14

#define IOWA_LWM2M_SOFTWARE_COMPONENT_ID_IDENTITY   0
#define IOWA_LWM2M_SOFTWARE_COMPONENT_ID_PACK       1
#define IOWA_LWM2M_SOFTWARE_COMPONENT_ID_VERSION    2
#define IOWA_LWM2M_SOFTWARE_COMPONENT_ID_ACTIVATE   3
#define IOWA_LWM2M_SOFTWARE_COMPONENT_ID_DEACTIVATE 4
#define IOWA_LWM2M_SOFTWARE_COMPONENT_ID_STATE      5

#define IOWA_LWM2M_SOFTWARE_COMPONENT_TYPE_IDENTITY   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_COMPONENT_TYPE_PACK       IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_SOFTWARE_COMPONENT_TYPE_VERSION    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_SOFTWARE_COMPONENT_TYPE_ACTIVATE   IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SOFTWARE_COMPONENT_TYPE_DEACTIVATE IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_SOFTWARE_COMPONENT_TYPE_STATE      IOWA_LWM2M_TYPE_BOOLEAN

#define IOWA_LWM2M_SOFTWARE_COMPONENT_OP_IDENTITY   IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_COMPONENT_OP_PACK       IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_COMPONENT_OP_VERSION    IOWA_OPERATION_READ
#define IOWA_LWM2M_SOFTWARE_COMPONENT_OP_ACTIVATE   IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SOFTWARE_COMPONENT_OP_DEACTIVATE IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_SOFTWARE_COMPONENT_OP_STATE      IOWA_OPERATION_READ

#define IOWA_LWM2M_SOFTWARE_COMPONENT_FLAGS_IDENTITY   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_COMPONENT_FLAGS_PACK       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_COMPONENT_FLAGS_VERSION    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_COMPONENT_FLAGS_ACTIVATE   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_COMPONENT_FLAGS_DEACTIVATE IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_SOFTWARE_COMPONENT_FLAGS_STATE      IOWA_RESOURCE_FLAG_OPTIONAL

/***************************************
 * Device Capabilities Management Object
 */

#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OBJECT_ID 15

#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_PROPERTY    0
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_GROUP       1
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_DESCRIPTION 2
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_ATTACHED    3
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_ENABLED     4
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_OP_ENABLE   5
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_OP_DISABLE  6
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_ID_NOTIFY      7

#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_PROPERTY    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_GROUP       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_DESCRIPTION IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_ATTACHED    IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_ENABLED     IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_OP_ENABLE   IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_OP_DISABLE  IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_TYPE_NOTIFY      IOWA_LWM2M_TYPE_BOOLEAN

#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_PROPERTY    IOWA_OPERATION_READ
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_GROUP       IOWA_OPERATION_READ
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_DESCRIPTION IOWA_OPERATION_READ
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_ATTACHED    IOWA_OPERATION_READ
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_ENABLED     IOWA_OPERATION_READ
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_OP_ENABLE   IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_OP_DISABLE  IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_OP_NOTIFY      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_PROPERTY    IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_GROUP       IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_DESCRIPTION IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_ATTACHED    IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_ENABLED     IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_OP_ENABLE   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_OP_DISABLE  IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_DEV_CAPABILITIES_MGMT_FLAGS_NOTIFY      IOWA_RESOURCE_FLAG_OPTIONAL

/*******************
 * Portfolio Object
 */

#define IOWA_LWM2M_PORTFOLIO_OBJECT_ID 16

#define IOWA_LWM2M_PORTFOLIO_ID_IDENTITY      0
#define IOWA_LWM2M_PORTFOLIO_ID_GET_AUTH_DATA 1
#define IOWA_LWM2M_PORTFOLIO_ID_AUTH_DATA     2
#define IOWA_LWM2M_PORTFOLIO_ID_AUTH_STATUS   3

#define IOWA_LWM2M_PORTFOLIO_TYPE_IDENTITY      IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_PORTFOLIO_TYPE_GET_AUTH_DATA IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_PORTFOLIO_TYPE_AUTH_DATA     IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_PORTFOLIO_TYPE_AUTH_STATUS   IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_PORTFOLIO_OP_IDENTITY      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_PORTFOLIO_OP_GET_AUTH_DATA IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_PORTFOLIO_OP_AUTH_DATA     IOWA_OPERATION_READ
#define IOWA_LWM2M_PORTFOLIO_OP_AUTH_STATUS   IOWA_OPERATION_READ

#define IOWA_LWM2M_PORTFOLIO_FLAGS_IDENTITY      (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_PORTFOLIO_FLAGS_GET_AUTH_DATA IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_PORTFOLIO_FLAGS_AUTH_DATA     (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_PORTFOLIO_FLAGS_AUTH_STATUS   IOWA_RESOURCE_FLAG_OPTIONAL

/*******************
 * Binary App Data Container Object
 */

#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OBJECT_ID 19

#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_ID_DATA               0
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_ID_DATA_PRIORITY      1
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_ID_DATA_CREATION_TIME 2
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_ID_DATA_DESCRIPTION   3
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_ID_DATA_FORMAT        4
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_ID_APP_ID             5

#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_TYPE_DATA               IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_TYPE_DATA_PRIORITY      IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_TYPE_DATA_CREATION_TIME IOWA_LWM2M_TYPE_TIME
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_TYPE_DATA_DESCRIPTION   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_TYPE_DATA_FORMAT        IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_TYPE_APP_ID             IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OP_DATA               (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OP_DATA_PRIORITY      (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OP_DATA_CREATION_TIME (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OP_DATA_DESCRIPTION   (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OP_DATA_FORMAT        (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_OP_APP_ID             (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_FLAGS_DATA               (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_FLAGS_DATA_PRIORITY      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_FLAGS_DATA_CREATION_TIME IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_FLAGS_DATA_DESCRIPTION   IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_FLAGS_DATA_FORMAT        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_BINARY_APP_DATA_CONTAINER_FLAGS_APP_ID             IOWA_RESOURCE_FLAG_OPTIONAL

/*******************
 * Event Log Object
 */

#define IOWA_LWM2M_EVENT_LOG_OBJECT_ID 20

#define IOWA_LWM2M_EVENT_LOG_ID_LOG_CLASS       4010
#define IOWA_LWM2M_EVENT_LOG_ID_LOG_START       4011
#define IOWA_LWM2M_EVENT_LOG_ID_LOG_STOP        4012
#define IOWA_LWM2M_EVENT_LOG_ID_LOG_STATUS      4013
#define IOWA_LWM2M_EVENT_LOG_ID_LOG_DATA        4014
#define IOWA_LWM2M_EVENT_LOG_ID_LOG_DATA_FORMAT 4015

#define IOWA_LWM2M_EVENT_LOG_TYPE_LOG_CLASS       IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_EVENT_LOG_TYPE_LOG_START       IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_EVENT_LOG_TYPE_LOG_STOP        IOWA_LWM2M_TYPE_UNDEFINED
#define IOWA_LWM2M_EVENT_LOG_TYPE_LOG_STATUS      IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_EVENT_LOG_TYPE_LOG_DATA        IOWA_LWM2M_TYPE_OPAQUE
#define IOWA_LWM2M_EVENT_LOG_TYPE_LOG_DATA_FORMAT IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_EVENT_LOG_OP_LOG_CLASS       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_EVENT_LOG_OP_LOG_START       IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_EVENT_LOG_OP_LOG_STOP        IOWA_OPERATION_EXECUTE
#define IOWA_LWM2M_EVENT_LOG_OP_LOG_STATUS      IOWA_OPERATION_READ
#define IOWA_LWM2M_EVENT_LOG_OP_LOG_DATA        IOWA_OPERATION_READ
#define IOWA_LWM2M_EVENT_LOG_OP_LOG_DATA_FORMAT (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_EVENT_LOG_FLAGS_LOG_CLASS       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_EVENT_LOG_FLAGS_LOG_START       IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_EVENT_LOG_FLAGS_LOG_STOP        IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_EVENT_LOG_FLAGS_LOG_STATUS      IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_EVENT_LOG_FLAGS_LOG_DATA        IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_EVENT_LOG_FLAGS_LOG_DATA_FORMAT IOWA_RESOURCE_FLAG_OPTIONAL

 /*******************
 * OSCoRE Object
 */

#define IOWA_LWM2M_OSCORE_OBJECT_ID 21

#define IOWA_LWM2M_OSCORE_ID_MASTER_SECRET  0
#define IOWA_LWM2M_OSCORE_ID_SENDER_ID      1
#define IOWA_LWM2M_OSCORE_ID_RECIPIENT_ID   2
#define IOWA_LWM2M_OSCORE_ID_AEAD_ALGORITHM 3
#define IOWA_LWM2M_OSCORE_ID_HMAC_ALGORITHM 4
#define IOWA_LWM2M_OSCORE_ID_MASTER_SALT    5

#define IOWA_LWM2M_OSCORE_TYPE_MASTER_SECRET  IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_OSCORE_TYPE_SENDER_ID      IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_OSCORE_TYPE_RECIPIENT_ID   IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_OSCORE_TYPE_AEAD_ALGORITHM IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_OSCORE_TYPE_HMAC_ALGORITHM IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_OSCORE_TYPE_MASTER_SALT    IOWA_LWM2M_TYPE_STRING

#define IOWA_LWM2M_OSCORE_OP_MASTER_SECRET  IOWA_OPERATION_NONE
#define IOWA_LWM2M_OSCORE_OP_SENDER_ID      IOWA_OPERATION_NONE
#define IOWA_LWM2M_OSCORE_OP_RECIPIENT_ID   IOWA_OPERATION_NONE
#define IOWA_LWM2M_OSCORE_OP_AEAD_ALGORITHM IOWA_OPERATION_NONE
#define IOWA_LWM2M_OSCORE_OP_HMAC_ALGORITHM IOWA_OPERATION_NONE
#define IOWA_LWM2M_OSCORE_OP_MASTER_SALT    IOWA_OPERATION_NONE

#define IOWA_LWM2M_OSCORE_FLAGS_MASTER_SECRET  IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_OSCORE_FLAGS_SENDER_ID      IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_OSCORE_FLAGS_RECIPIENT_ID   IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_OSCORE_FLAGS_AEAD_ALGORITHM IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_OSCORE_FLAGS_HMAC_ALGORITHM IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_OSCORE_FLAGS_MASTER_SALT    IOWA_RESOURCE_FLAG_OPTIONAL

/*******************
 * Virtual Observe Notify Object
 */

#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_OBJECT_ID 22

#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_ID_OBSERVE_LINKS    0
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_ID_REPORT           1
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_ID_RESOURCE_FILTER  2
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_ID_REPORT_LINKS     3
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_ID_OBSERVE_RELATION 4

#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_TYPE_OBSERVE_LINKS    IOWA_LWM2M_TYPE_CORE_LINK
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_TYPE_REPORT           IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_TYPE_RESOURCE_FILTER  IOWA_LWM2M_TYPE_BOOLEAN
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_TYPE_REPORT_LINKS     IOWA_LWM2M_TYPE_CORE_LINK
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_TYPE_OBSERVE_RELATION IOWA_LWM2M_TYPE_INTEGER

#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_OP_OBSERVE_LINKS    (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_OP_REPORT           IOWA_OPERATION_READ
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_OP_RESOURCE_FILTER  (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_OP_REPORT_LINKS     (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_OP_OBSERVE_RELATION (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)

#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_FLAGS_OBSERVE_LINKS    (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_FLAGS_REPORT           IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_FLAGS_RESOURCE_FILTER  IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_FLAGS_REPORT_LINKS     (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_OPTIONAL)
#define IOWA_LWM2M_VIRTUAL_OBSERVE_NOTIFY_FLAGS_OBSERVE_RELATION IOWA_RESOURCE_FLAG_OPTIONAL

/************************
 * AT Command Object
 */

#define IOWA_LWM2M_AT_COMMAND_OBJECT_ID 10251

#define IOWA_LWM2M_AT_COMMAND_ID_COMMAND   0
#define IOWA_LWM2M_AT_COMMAND_ID_RESPONSE  1
#define IOWA_LWM2M_AT_COMMAND_ID_STATUS    2
#define IOWA_LWM2M_AT_COMMAND_ID_TIMEOUT   3
#define IOWA_LWM2M_AT_COMMAND_ID_RUN       4

#define IOWA_LWM2M_AT_COMMAND_TYPE_COMMAND     IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_AT_COMMAND_TYPE_RESPONSE    IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_AT_COMMAND_TYPE_STATUS      IOWA_LWM2M_TYPE_STRING
#define IOWA_LWM2M_AT_COMMAND_TYPE_TIMEOUT     IOWA_LWM2M_TYPE_INTEGER
#define IOWA_LWM2M_AT_COMMAND_TYPE_RUN         IOWA_LWM2M_TYPE_UNDEFINED

#define IOWA_LWM2M_AT_COMMAND_OP_COMMAND       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_AT_COMMAND_OP_RESPONSE      IOWA_OPERATION_READ
#define IOWA_LWM2M_AT_COMMAND_OP_STATUS        IOWA_OPERATION_READ
#define IOWA_LWM2M_AT_COMMAND_OP_TIMEOUT       (IOWA_OPERATION_READ | IOWA_OPERATION_WRITE)
#define IOWA_LWM2M_AT_COMMAND_OP_RUN           IOWA_OPERATION_EXECUTE

#define IOWA_LWM2M_AT_COMMAND_FLAGS_COMMAND     IOWA_RESOURCE_FLAG_MANDATORY
#define IOWA_LWM2M_AT_COMMAND_FLAGS_RESPONSE    (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_AT_COMMAND_FLAGS_STATUS      (IOWA_RESOURCE_FLAG_MULTIPLE | IOWA_RESOURCE_FLAG_MANDATORY)
#define IOWA_LWM2M_AT_COMMAND_FLAGS_TIMEOUT     IOWA_RESOURCE_FLAG_OPTIONAL
#define IOWA_LWM2M_AT_COMMAND_FLAGS_RUN         IOWA_RESOURCE_FLAG_MANDATORY

#ifdef __cplusplus
}
#endif

#endif
